{% set name = "brainglobe-atlasapi" %}
{% set version = "2.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 7c2908ab763ae7d5f3539e40c53868a9739e6b992da6029cf892e188c7c2b0c4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=45
    - wheel
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.9
    - brainglobe-space >=1.0.0
    - click
    - meshio
    - numpy
    - pandas
    - pyarrow
    - requests
    - rich >=9.0.0
    - tifffile
    - tqdm >=4.46.1
    - treelib
    - vtk

test:
  imports:
    - brainglobe_atlasapi
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/brainglobe/brainglobe-atlasapi
  summary: A lightweight python module to interact with and generate atlases for systems neuroscience.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - willGraham01
    - adamltyson
    - alessandrofelder
